const CartType = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  add_item: 'ADD_ITEMS',
  CLEAR_ITEM_FROMCART: 'CLEAR_ITEM_FROMCART',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_CART: 'CLEAR_CART'
};
export default CartType;
