const userType = {
 
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",
  SIGNIN_SUCESS: "SIGNIN_SUCESS",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  CHECK_USER_PERSIST:'CHECK_USER_PERSIST',
  SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE:'SIGN_OUT_FAILURE',
  SIGN_OUT_START:'SIGN_OUT_START',
  SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE:'SIGN_UP_FAILURE',
  SIGN_UP_START:'SIGN_OUT_START'
};

export default userType;
